-- ============================================================
-- QUERY 15: Service Type Revenue & Ticket Analysis
-- ============================================================
-- Database: restaurant_analytics
-- Author: Ivan Jarpa
-- Date: February 2026
-- Complexity: ⭐⭐⭐⭐ Advanced
-- ============================================================
-- Business Question:
-- Which service types generate the highest average ticket value,
-- and how do they compare against each other and the overall average?
-- ============================================================
-- Key Concepts Demonstrated:
-- - Multiple CTEs for modular logic (3 levels)
-- - Window functions: MAX() OVER(), AVG() OVER(), ROW_NUMBER()
-- - Complex metric calculations (ticket promedio, differences)
-- - CASE WHEN for conditional text output
-- - Multi-table JOINs between CTEs
-- ============================================================

USE restaurant_analytics;

WITH tab_pedidos AS (
    -- CTE1: Count total orders by service type
    SELECT
        tipo_servicio,
        COUNT(*) AS total_pedidos
    FROM pedidos
    GROUP BY tipo_servicio
),
tab_revenue AS (
    -- CTE2: Calculate total revenue by service type
    SELECT
        p.tipo_servicio,
        SUM(dp.cantidad * dp.precio_unitario) AS revenue_total
    FROM pedidos p
    INNER JOIN detalle_pedidos dp
        ON p.pedido_id = dp.pedido_id
    GROUP BY p.tipo_servicio
),
tab_analisis AS (
    -- CTE3: Calculate ticket average and comparative metrics
    SELECT
        tp.tipo_servicio,
        tp.total_pedidos,
        tr.revenue_total,
        tr.revenue_total / tp.total_pedidos AS ticket_promedio,
        ROW_NUMBER() OVER(
            ORDER BY tr.revenue_total / tp.total_pedidos DESC
        ) AS ranking_ticket,
        MAX(tr.revenue_total / tp.total_pedidos) OVER() AS max_ticket,
        AVG(tr.revenue_total / tp.total_pedidos) OVER() AS avg_ticket
    FROM tab_pedidos tp
    INNER JOIN tab_revenue tr
        ON tp.tipo_servicio = tr.tipo_servicio
)
-- Final query: Comparative analysis with position classification
SELECT
    tipo_servicio,
    total_pedidos,
    revenue_total,
    ticket_promedio,
    ranking_ticket,
    ticket_promedio - max_ticket AS diferencia_vs_top,
    CASE
        WHEN ticket_promedio > avg_ticket THEN 'Arriba del promedio'
        WHEN ticket_promedio < avg_ticket THEN 'Abajo del promedio'
        ELSE 'Igual al promedio'
    END AS posicion
FROM tab_analisis
ORDER BY ticket_promedio DESC;

-- ============================================================
-- Expected Output Columns:
-- ============================================================
-- tipo_servicio        : Service channel (Mesa/Delivery/Para Llevar)
-- total_pedidos        : Number of orders for this service type
-- revenue_total        : Total revenue generated by service type
-- ticket_promedio      : Average ticket value (revenue / orders)
-- ranking_ticket       : Rank by average ticket (1 = highest)
-- diferencia_vs_top    : Difference vs highest ticket average
-- posicion             : Classification vs overall average
-- ============================================================

-- ============================================================
-- Business Value:
-- ============================================================
-- - Identifies most profitable service channels
-- - Supports pricing strategy decisions
-- - Highlights revenue optimization opportunities
-- - Enables service-level performance benchmarking
-- ============================================================

-- ============================================================
-- Technical Notes:
-- ============================================================
-- Window Functions Used:
-- - MAX() OVER(): Gets highest ticket average across all types
-- - AVG() OVER(): Calculates overall average ticket
-- - ROW_NUMBER() OVER(): Assigns ranking by ticket value
--
-- These window functions repeat the same value on each row
-- without collapsing rows, enabling row-by-row comparisons.
--
-- CTE Architecture:
-- Level 1 (tab_pedidos): Base aggregation - order count
-- Level 2 (tab_revenue): Base aggregation - revenue calculation
-- Level 3 (tab_analisis): Derived metrics with window functions
-- Final SELECT: Business logic (differences, classification)
-- ============================================================
